CREATE TABLE `KTS`.`KTS_TEST` (
  `TEST_SEQ` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(100),
  PRIMARY KEY (`TEST_SEQ`)
);
CREATE TABLE `KTS`.`KTS_TESTCASE` (
  `TESTCASE_SEQ` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(150),
  PRIMARY KEY (`TESTCASE_SEQ`)
);
CREATE TABLE `KTS`.`TEST_REL_TESTCASE` (
  `TEST_SEQ` BIGINT NOT NULL,
  `TESTCASE_SEQ` BIGINT NOT NULL,
  `ORDER` INT NOT NULL,
  PRIMARY KEY (`TEST_SEQ`, `TESTCASE_SEQ`, `ORDER`)
);
