TRUNCATE TABLE TEST_REL_TESTCASE;
INSERT  INTO `TEST_REL_TESTCASE`(`TEST_SEQ`,`TESTCASE_SEQ`,`LIST_INDEX`) VALUES
(1,1,1),
(1,2,2),
(1,2,3),
(1,2,4),
(1,2,5),
(1,3,6),
(2,1,4),
(2,2,2),
(2,2,3),
(2,3,1);

-- step 1. 해당 테스트케이스와 연관된 모든 관계 삭제
DELETE FROM TEST_REL_TESTCASE WHERE TESTCASE_SEQ = 2;

-- step 2. 관계 테이블 업데이트
SET @rownum:=0;
UPDATE TEST_REL_TESTCASE a INNER JOIN (SELECT res.RELATION_SEQ, res.TEST_SEQ, res.rNum AS LIST_INDEX, res.TESTCASE_SEQ FROM (
	SELECT(CASE @val WHEN t1.TEST_SEQ THEN @rownum:=@rownum+1 ELSE @rownum:=1 END) AS rNum, (@val:=t1.TEST_SEQ) temp, t1.*
	FROM TEST_REL_TESTCASE t1
	ORDER BY t1.TEST_SEQ, t1.LIST_INDEX
) res) b ON a.RELATION_SEQ = b.RELATION_SEQ 
SET a.LIST_INDEX = b.LIST_INDEX;

-- 결과 확인
SELECT * FROM TEST_REL_TESTCASE ORDER BY TEST_SEQ, LIST_INDEX;
