TRUNCATE TABLE TEST_REL_TESTCASE;
INSERT  INTO `TEST_REL_TESTCASE`(`TEST_SEQ`,`TESTCASE_SEQ`,`LIST_INDEX`) VALUES
(1,1,1),
(1,2,2),
(1,2,3),
(1,2,4),
(1,2,5),
(1,3,6),
(2,1,4),
(2,2,2),
(2,2,3),
(2,3,1);

-- step 1. 해당 테스트케이스를 삭제하면 영향을 받는 테스트 조회 -> 리스트로 메모리에 저장
SELECT TEST_SEQ FROM TEST_REL_TESTCASE WHERE TESTCASE_SEQ = 2 GROUP BY TEST_SEQ;

-- step 2. 해당 테스트케이스와 연관된 모든 관계 삭제
DELETE FROM TEST_REL_TESTCASE WHERE TESTCASE_SEQ = 2;

-- step 3. 갱신할 값 생성
SET @rownum:=0;
SELECT res.RELATION_SEQ, res.TEST_SEQ, res.rNum AS LIST_INDEX, res.TESTCASE_SEQ FROM (
	SELECT(CASE @val WHEN t1.TEST_SEQ THEN @rownum:=@rownum+1 ELSE @rownum:=1 END) AS rNum, (@val:=t1.TEST_SEQ) temp, t1.*
	FROM TEST_REL_TESTCASE t1
	ORDER BY t1.TEST_SEQ, t1.LIST_INDEX
) res;

-- step 4. 딕셔너리의 값대로 수치 업데이트
UPDATE TEST_REL_TESTCASE SET LIST_INDEX = 1 WHERE RELATION_SEQ = 1;
UPDATE TEST_REL_TESTCASE SET LIST_INDEX = 2 WHERE RELATION_SEQ = 6;
UPDATE TEST_REL_TESTCASE SET LIST_INDEX = 1 WHERE RELATION_SEQ = 10;
UPDATE TEST_REL_TESTCASE SET LIST_INDEX = 2 WHERE RELATION_SEQ = 7;

-- 결과 확인
SELECT * FROM TEST_REL_TESTCASE ORDER BY TEST_SEQ, LIST_INDEX;
